name: API Container Images

on:
 push:
  paths:
    - 'api/**'
    - 'test/**'
    - '.github/workflows/api_container_images.yaml'
  pull_request:
    paths:
    - 'api/**'
    - 'test/**'
    - '.github/workflows/api_container_images.yaml'

env:
  IMAGE: "sqlops/ansible-pyodbc"
  DOCKERFILE: "./ansible/Dockerfile"
  ENV_FILE: "./ansible/.env"

jobs:
  build:
    name: "Build OCI image: ${{ matrix.image }}"
    strategy:
      matrix:
        image:
          - basic-flask-restful-api
          - basic-bottle-restful-api
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Set ENV variables
        run: |
          cat ./api/${{ matrix.image }}/.env >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Login to quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }} 

      - name: Build & Push image to Docker
        id: dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./api/${{ matrix.image }})
          push: true
          tags: docker.io/${{ matrix.image }}:${{ env.SEMVER_MAJOR }},docker.io/${{ matrix.image }}:${{ env.SEMVER_MINOR }},docker.io/${{ matrix.image }}:${{ env.SEMVER_PATCH }},docker.io/${{ matrix.image }}:${{ env.SEMVER_TAG }},docker.io/${{ matrix.image }}:latest
          file: ./api/${{ matrix.image }})"/Dockerfile
          platforms: linux/amd64
      
      - name: Push image to Quay
        id: quay
        uses: docker/build-push-action@v2
        with:
          context: ./api/${{ matrix.image }})
          push: true
          tags: quay.io/${{ matrix.image }}:${{ env.SEMVER_MAJOR }},quay.io/${{ matrix.image }}:${{ env.SEMVER_MINOR }},quay.io/${{ matrix.image }}:${{ env.SEMVER_PATCH }},quay.io/${{ matrix.image }}:${{ env.SEMVER_TAG }},quay.io/${{ matrix.image }}:latest
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64